version: '3'
services:
   db:
     container_name: db
     image: mysql:latest
     volumes:
       - ./db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: easytoguess
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: eveneasier

   wordpress:
     container_name: wordpress
     depends_on:
       - db
     image: wordpress:latest
     restart: always
     volumes:
       - ./wordpress:/var/www/html/wp-content
     ports:
      - 8080:80     
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: eveneasier
       WORDPRESS_DB_NAME: wordpress

   nginx:
      container_name: nginx
      image: nginx:latest
      restart: unless-stopped
      ports:
      - 80:80
      volumes:
      - ./nginx/conf:/etc/nginx/conf.d
   redis:
    container_name: redis
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"

       
